### ISSUE TITLE
首页标签未翻译

### ISSUE THREAD

**Issue by 63510** [SunBrook/EHentai.Tags.CN#10]
[https://i.postimg.cc/ZKxTVCL5/QQ-20230704222028.png](url)

如图可以看出脚本是有在运行的，画廊的标签却没有被翻译，
但是如果点开单独的画廊标签又能正确被翻译

**Comment by 63510** [comment]
[![QQ-20230704222028.png](https://i.postimg.cc/ZKxTVCL5/QQ-20230704222028.png)](https://postimg.cc/QHVGMNP2)

**Comment by SunBrook** [comment]
好的，不过要等到周六日处理，平时没空弄

**Comment by SunBrook** [comment]
我上去看了，可能是你的脚本版本太低了，现在版本是 3.15.8 如果不是需要更新到最新版本

**Comment by SunBrook** [comment]
![Snipaste_2023-07-08_16-05-08](https://github.com/SunBrook/EHentai.Tags.CN/assets/14243713/98e3c0d4-9f22-4acd-8f5c-d226f2a60e40)

**Comment by 63510** [comment]
已经是最新版本了
[![QQ-20230708220531.png](https://i.postimg.cc/VsCKGyLB/QQ-20230708220531.png)](https://postimg.cc/5jf5yRz6)

以及有时候会出现这种情况，部分画廊翻译了，但部分没有，
[![QQ-20230708220717.png](https://i.postimg.cc/j2bP3FZZ/QQ-20230708220717.png)](https://postimg.cc/hz2XfpFd)

唯一比较确定的就是当选取tag进行筛选时几乎不作用
[![QQ-20230708221247.png](https://i.postimg.cc/wTsYQ4nS/QQ-20230708221247.png)](https://postimg.cc/TpGsR0d9)

我先尝试下重装脚本，看能不能有点改善orz，或者大佬你要查看哪些参数啥的

**Comment by SunBrook** [comment]
这个网站还有装其他脚本吗，挨个排查一下

**Comment by 63510** [comment]
首页的应该是跟这个脚本冲突了，这个脚本解锁 Hath Perks后，翻页转化为了瀑布流，导致第二页开始都未进行翻译，不关闭脚本而只关闭瀑布流也会导致第二页开始无法翻译，且首页时不时也会出现未翻译的问题。
https://sleazyfork.org/scripts/34422-unlock-hath-perks/code/Unlock%20Hath%20Perks.user.js

然后是类型为   https://exhentai.org/tag/*  的仍然无法正常运行脚本，即不能直接在画廊中点击标签进行拓展搜索，选择手打输入，即转换为  https://exhentai.org/?f_search=  后可正常运行

另外我尝试在脚本的匹配网站中加入了 // @match        *://exhentai.org/tag/*  也无法正常起效

tag形式，未能正常运行
[![QQ-20230709155536.png](https://i.postimg.cc/vmWh5J4t/QQ-20230709155536.png)](https://postimg.cc/gw23WBqx)

搜索形式，正常运行
[![QQ-20230709155652.png](https://i.postimg.cc/c15RtxDN/QQ-20230709155652.png)](https://postimg.cc/bdkDKhc6)

**Comment by SunBrook** [comment]
这个无限翻页的脚本应该是重新加载页面导致页面内容被覆盖了，无法同时使用这两个脚本，这种翻页的功能后期可以考虑加进来
