### ISSUE TITLE
首页能正常翻译标签，但作品页不行

### ISSUE THREAD

**Issue by 63510** [SunBrook/EHentai.Tags.CN#11]
如图，在搜索页是能正常对标签进行翻译的，但进入到作品页后就不行了
[![QQ-20231028110618.jpg](https://i.postimg.cc/HkJqxHvV/QQ-20231028110618.jpg)](https://postimg.cc/K12qpX22)
[![QQ-20231028110627.jpg](https://i.postimg.cc/sxPXGSb2/QQ-20231028110627.jpg)](https://postimg.cc/Cn1YWZhy)
使用版本为3.15.8
[![QQ-20231028110916.jpg](https://i.postimg.cc/XNQmkXTr/QQ-20231028110916.jpg)](https://postimg.cc/Wtq52ppV)

**Comment by SunBrook** [comment]
过两天看吧，这两天无法访问网站了

**Comment by SunBrook** [comment]
已经修复，请更新到3.15.9版本。https://sleazyfork.org/zh-CN/scripts/441232
