### ISSUE TITLE
部分画廊的种子下载页面的第一个种子格式会乱，没有下载按钮

### ISSUE THREAD

**Issue by CircleRuler** [SunBrook/EHentai.Tags.CN#13]
如题，目前试了下部分新的画廊没有这个问题，如https://exhentai.org/g/2855796/12f14293ed/

发现bug时在下载的作品，示例https://exhentai.org/g/2571081/8be4066047/
（↑显示有4个，点进去发现只有三个，第一个的css乱掉了还是能看见下载数但是没有下载按钮）

（又仔细统计了一下没问题的画廊的特点应该是后面更新过的老画廊，种子是旧版本的，会显示本作品共有 There are no up-to-date torrents for this gallery. 个种子。，这样的不会被吞掉第一个种子。其他的应该都有问题）

**Comment by SunBrook** [comment]
问题已修复，请更新到最新版本
