### ISSUE TITLE
每次进入EX页面后页面会无响应一段时间

### ISSUE THREAD

**Issue by Liiuse** [SunBrook/EHentai.Tags.CN#2]
每次进入ex主页包括搜索后页面（每次搜索都是），就会无响应5-8秒，期间笔记本的风扇会增加转速，但是CPU、显卡、内存的占用却都没有提高…
我是用的是edge+油猴4.16.1版本

**Comment by SunBrook** [comment]
先换成谷歌浏览器吧，我不确定是不是 Edge 浏览器的问题，还是油猴插件，或者脚本的问题。谷歌浏览器运行是流畅的

**Comment by SunBrook** [comment]
已经找到问题，抽空重写相关代码

**Comment by SunBrook** [comment]
已经修复，后续会继续优化
