### ISSUE TITLE
类别错位

### ISSUE THREAD

**Issue by MC-cookies** [SunBrook/EHentai.Tags.CN#3]
如图
![image](https://user-images.githubusercontent.com/117754398/204121320-decc7d5f-a426-4342-b279-4d52e35f9dae.png)

**Comment by MC-cookies** [comment]
之前是好好的,今天打开突然就成这样了
试过重装但是好像没用

**Comment by MC-cookies** [comment]
edge版本 107.0.1418.56 (正式版本) (64 位)
油猴版本 v4.16.1
脚本版本 3.15.1

**Comment by SunBrook** [comment]
你的浏览器缩放了，Ctrl + 0，即可复原

**Comment by SunBrook** [comment]
你的壁纸真可爱

**Comment by SunBrook** [comment]
如果可以用，尽量用谷歌浏览器。现在Edge感觉有点问题

**Comment by SunBrook** [comment]
问题是否得到了解决，如果解决了请关闭该提问，谢谢！
