### ISSUE TITLE
上传页网址未被匹配

### ISSUE THREAD

**Issue by status102** [SunBrook/EHentai.Tags.CN#4]
上传页网址：https://upld.e-hentai.org/manage
不被e-hentai.org/\*匹配，修改为\*.e-hentai.org/*可解决

**Comment by SunBrook** [comment]
已更新，请更新脚本，不过该页面的内容没空汉化，需要时间去弄，这块也不是我最关注的事情，可能会排期到最后去做。确认不误就关闭这个问题吧，谢谢反馈💕

**Comment by status102** [comment]
没事w
