### ISSUE TITLE
对画廊的标签进行操作后，标签变回英文显示

### ISSUE THREAD

**Issue by status102** [SunBrook/EHentai.Tags.CN#5]
打开画廊后，此时标签正常被翻译成中文。然后，添加新标签 / 对标签投标后，标签区域会变回英文
比如：
其他:变体集
↓
other:variant set

**Comment by SunBrook** [comment]
能否详细说明，没确定是什么问题

**Comment by status102** [comment]
刚打开画廊的时候：
![image](https://user-images.githubusercontent.com/102887808/220929218-7adee925-247c-41bd-9231-baa1c32de251.png)
然后选中标签进行投票：
![image](https://user-images.githubusercontent.com/102887808/220929316-fabf1a81-863a-42bc-87cd-dfd4bd1efed0.png)
之后就会：
![image](https://user-images.githubusercontent.com/102887808/220929359-27767dc6-d4d4-412f-8d32-ec6f7e72af6d.png)

**Comment by SunBrook** [comment]
明白了，不过看好不好改，这个不是我汉化的重点😂希望你能理解

**Comment by status102** [comment]
> 明白了，不过看好不好改，这个不是我汉化的重点😂希望你能理解

单纯的做一个反馈

**Comment by SunBrook** [comment]
以前尝试改过，后面不稳定就没有汉化了，替换有点复杂🤣，现在还有很多bug需要修复，我抽时间在改
